version: "3"
services:
  frontend:
    build: ./frontend
    restart: always

  backend:
    build: ./backend
    restart: always
    links:
      - kms
    depends_on:
      - kms

  kms:
    restart: always
    image: kurento/kurento-media-server:6.10.0

networks:
  default:
    external:
      name: demoserver_network_1
